### ISSUE TITLE
Substition rules?

### ISSUE THREAD

**Issue by hharocha** [bozsahin/ccg-latex#1]
Hi Bozsahin!

Thank you very much for uploading this usefull code! I have a question about the inference rules. Is it possible to implement it with more rules (like backward substitution (<S), forward substitution (>S), the respective crossing ones or the  the conjunction<Φ>)?

Thank you very much in advance!
Hector

**Comment by bozsahin** [comment]
Hello Hector. thanks for using the code.


On Sat, Oct 28, 2017 at 6:34 PM, hharocha <notifications@github.com> wrote:

> Hi Bozsahin!
>
> Thank you very much for uploading this usefull code! I have a question
> about the inference rules. Is it possible to implement it with more rules
> (like backward substitution (<S), forward substitution (>S),
>

By 'implement' i assume you mean using them in display of derivations. Yes
they are all in there. S is \combs. Directional variants are \cgfs for >S,
\cgbs for <S,
\cgfsx for >Sx etc. Powers are there too, as \combss for S^2 etc.

If you mean using them in parsing, they are implemented here:
https://github.com/bozsahin/ccglab


> the respective crossing ones or the the conjunction<Φ>)?
>

Phi is \combphi in ccg-latex. There is no directional variant defined
because in CCG Phi is lexical. Check ccglab for its implementation using @X
categories.


all best.
-cem

Thank you very much in advance!

**Comment by bozsahin** [comment]
Directional variants of all syntactic combinators are included.
